#!/bin/sh -e

ENABLE_GRAPHICS=false

if dpkg -l | egrep -q "ii  (xwayland|xserver-xorg) "; then
  ENABLE_GRAPHICS=true
fi

PACKAGES="screen bat zsh curl jq htop btop lsd stow"
if [ "${ENABLE_GRAPHICS}" = "true" ]; then
  PACKAGES="$PACKAGES kitty fonts-powerline fonts-ubuntu fonts-font-awesome fonts-powerline"
fi

sudo apt install $PACKAGES

git submodule update --init

./bin/ohmyzsh-install

ln -fs ~/.dotconfig/zsh/zshrc ~/.zshrc
mkdir -p ~/.zsh

ln -fs ~/.dotconfig/screen/screenrc ~/.screenrc
if [ ! -L ~/.bin ]; then
  ln -fs ~/.dotconfig/bin ~/.bin
fi

ln -fs ~/.dotconfig/git/config ~/.gitconfig
# ln -fs ~/.dotconfig/ruby/irbrc ~/.irbrc

if [ "${ENABLE_GRAPHICS}" = "true" ]; then
  if [ ! -L ~/.doom.d ]; then
    ln -fs ~/.dotconfig/doom-emacs ~/.doom.d
  fi
fi

ln -fs ~/.dotconfig/starship.toml ~/.config/starship.toml

PATH="./bin:$PATH"

./bin/dust-install
./bin/mcfly-install
./bin/starship-install
./bin/difftastic-install

cd `dirname $0`

./tmux/install
stow tmux
./tmux/setup

if [ "${ENABLE_GRAPHICS}" = "true" ]; then
  ./kitty/install
  stow kitty

  stow gtk
  ./gtk/setup
  
  stow gedit
fi
