#!/bin/sh -e

PACKAGES="screen kitty bat zsh curl jq htop btop fonts-powerline fonts-ubuntu fonts-ubuntu-console"
sudo apt install $PACKAGES

./bin/ohmyzsh-install

ln -fs ~/.dotconfig/zsh/zshrc ~/.zshrc
mkdir -p ~/.zsh

ln -fs ~/.dotconfig/screen/screenrc ~/.screenrc
if [ ! -L ~/.bin ]; then
  ln -fs ~/.dotconfig/bin ~/.bin
fi

ln -fs ~/.dotconfig/git/config ~/.gitconfig
# ln -fs ~/.dotconfig/ruby/irbrc ~/.irbrc

ln -fs ~/.dotconfig/kitty/kitty.conf ~/.config/kitty/kitty.conf
ln -fs ~/.dotconfig/starship.toml ~/.config/starship.toml

I3_CONFIG=~/.dotconfig/i3/config-$(hostname)
if [ -f ${I3_CONFIG} ]; then
  ln -fs  ${I3_CONFIG} ~/.config/i3/config
fi

ln -fs ~/.dotconfig/doom-emacs ~/.doom.d

PATH="./bin:$PATH"

./bin/dust-install
./bin/mcfly-install
./bin/starship-install
