HISTFILE=~/.zsh/history
HISTSIZE=4000
SAVEHIST=4000
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY
setopt HIST_FIND_NO_DUPS
setopt INC_APPEND_HISTORY
