#!/bin/sh -e

PACKAGES="i3 picom playerctl feh variety adwaita-icon-theme polybar"
sudo apt install $PACKAGES

# Setup files create with LxAppareance
ln -fs ~/.dotconfig/i3/gtk/gtkrc ~/.gtkrc-2.0

mkdir -p ~/.icons/default
ln -fs ~/.dotconfig/i3/gtk/icons.theme ~/.icons/default/index.theme

ln -fs ~/.dotconfig/i3/Xresources ~/.Xresources
xrdb ~/.Xresources

# Polybar
mkdir -p ~/.config/polybar
ln -fs ~/.dotconfig/i3/polybar.ini ~/.config/polybar/config.ini
